### ISSUE TITLE
[server notice: tebex_not_set]

### ISSUE THREAD

**Issue by Nikitapjk** [BuycraftPlugin/Tebex-FiveM#5] opened 2021-08-29 07:51 UTC

**Comment by entity** [comment] 2023-05-10 12:04
Hi there,

Thank you for reporting this issue. Unfortunately, we're unable to investigate this bug without further information or steps to reproduce it.

Since we have not been able to reproduce the issue and we do not have enough context to investigate it further, we will be closing this GitHub ticket. However, we encourage you to provide us with additional details or steps to reproduce the issue, so we can take a closer look.

Please feel free to open a new ticket with the additional information, and we'll be happy to investigate the issue further.

Thank you for your understanding and for your continued support of Tebex.

Best regards,
The Integrations Team.

**Closed as completed** 2023-05-10 13:48 UTC
